@testitem "Protobuf extension" tags=[:extension] setup=[NitroCommon] begin
using HTTP
using ProtoBuf
using Nitro: protobuf

include(".messages/people_pb.jl");
using .people_pb: People, Person

include(".messages/test_pb.jl");
using .test_pb: MyMessage 

@testset "Protobuf decoder test" begin
    message = MyMessage(-1, ["a", "b"])
    req::HTTP.Request = protobuf(message, "/data")

    decoded_msg = protobuf(req, MyMessage)

    @test decoded_msg isa MyMessage
    @test decoded_msg.a == -1
    @test decoded_msg.b == ["a", "b"]
end

@testset "Protobuf People Decoder test" begin
    message = People([
        Person("John Doe", 20),
        Person("Jane Doe", 25),
        Person("Alice", 30),
        Person("Bob", 35),
        Person("Charlie", 40)
    ])

    req::HTTP.Request = protobuf(message, "/data", method="POST")

    decoded_msg = protobuf(req, People)

    @test decoded_msg isa People
    for person in decoded_msg.people
        @test person isa Person
    end
end


@testset "Protobuf encoder test" begin

    message = MyMessage(-1, ["a", "b"])
    response = protobuf(message)

    @test response isa HTTP.Response
    @test response.status == 200
    @test response.body isa Vector{UInt8}
    @test HTTP.header(response, "Content-Type") == "application/octet-stream"
    @test HTTP.header(response, "Content-Length") == string(sizeof(response.body))
end


@testset "Protobuf People encoder test" begin
    message = People([
        Person("John Doe", 20),
        Person("Jane Doe", 25),
        Person("Alice", 30),
        Person("Bob", 35),
        Person("Charlie", 40)
    ])

    response = protobuf(message)

    @test response isa HTTP.Response
    @test response.status == 200
    @test response.body isa Vector{UInt8}
    @test HTTP.header(response, "Content-Type") == "application/octet-stream"
    @test HTTP.header(response, "Content-Length") == string(sizeof(response.body))
end

# -- #325: the decode is bounded ---------------------------------------------------------------
#
# `test_pb` and `people_pb` were generated by ProtoBuf.jl 1.0.15, whose sub-message decoding
# upstream replaces with its own decoder; `bounds_pb` is current codegen, which keeps the decoder
# it is given, and carries the field shapes the old two lack. Both styles have to hold.
#
# Every rejected body below decodes WITHOUT complaint on the unbounded decoder, or allocates its
# claimed length first -- so none of these passes unless the bound is there. Nothing nests past
# 1,000 levels: an unbounded decode of the overflow-depth bodies (a million group tags, 200,000
# nested `Node`s) takes the process down, so a regressed bound must fail an assertion here rather
# than kill the test worker (#254, #301). The cap is checked on the way in at level 101, so a
# deeper body adds nothing but that risk.
include(".messages/bounds_pb.jl");
using .bounds_pb: Blob, Node, Holder
include(".messages/bounds2_pb.jl");      # proto2, for `required` message fields
using .bounds2_pb: Point, Line, Drawing, Tag, Labeled, Row, Table, Bag, Box

@testset "Protobuf bounded decoding (#325)" begin
    req(bytes) = HTTP.Request("POST", "/data", [], bytes)
    decoded(bytes, T) = protobuf(req(bytes), T)
    refused(bytes, T) = try
        protobuf(req(bytes), T)
        "decoded"
    catch e
        e isa ArgumentError ? e.msg : "threw $(typeof(e))"
    end
    varint(n) = (o = UInt8[]; while n >= 0x80; push!(o, UInt8(n & 0x7f) | 0x80); n >>= 7; end; push!(o, UInt8(n)); o)
    groups(n) = vcat(fill(0x1b, n), fill(0x04, n))     # field 3, START_GROUP ... END_GROUP
    # `n` nested `Node.child`s, built outside-in: each level's prefix is the length of the rest.
    function nodes(n)
        len = zeros(Int, n + 1)
        for k in 1:n
            len[k+1] = 1 + length(varint(len[k])) + len[k]
        end
        body = UInt8[]
        for k in n:-1:1
            push!(body, 0x12); append!(body, varint(len[k]))
        end
        return body
    end

    PREFIX = "protobuf length prefix exceeds the remaining body"
    DEPTH  = "protobuf message nests deeper than 100 levels"

    @testset "a length prefix longer than the body is refused before it is allocated" begin
        # `0a` = field 1, length-delimited; `80 80 80 20` = 64 MiB; `ff ff ff ff 0f` = 4 GiB.
        @test refused(UInt8[0x0a, 0x80, 0x80, 0x80, 0x20], Person) == PREFIX
        @test refused(UInt8[0x0a, 0xff, 0xff, 0xff, 0xff, 0x0f], Person) == PREFIX
        # Inside a sub-message, which the old codegen decodes on a decoder upstream builds.
        @test refused(UInt8[0x0a, 0x05, 0x0a, 0x80, 0x80, 0x80, 0x20], People) == PREFIX
        # `MyMessage`'s field 1 is `sint32` and decodes as a varint whatever the wire type says;
        # its string is field 2.
        @test refused(UInt8[0x12, 0x80, 0x80, 0x80, 0x20], MyMessage) == PREFIX
        # Packed fixed-width runs allocate from the prefix too.
        for tag in (0x12, 0x1a, 0x22)                    # fixed32, float, bool
            @test refused(UInt8[tag, 0x80, 0x80, 0x80, 0x20], Blob) == PREFIX
        end

        # Upstream allocates the 64 MiB and only then finds the body short.
        attempt(bytes) = try protobuf(req(bytes), Person) catch e; e end
        body = UInt8[0x0a, 0x80, 0x80, 0x80, 0x20]
        attempt(body); attempt(body)
        @test (@allocated attempt(body)) < 2^20
    end

    @testset "a lying prefix is refused, not silently truncated" begin
        # A `bytes` field claiming 16 bytes with 2 present decoded upstream as `[0x01, 0x02]`.
        @test refused(UInt8[0x0a, 0x10, 0x01, 0x02], Blob) == PREFIX
        # So did an unknown length-delimited field (field 4 here) -- skipped as far as it could go.
        @test refused(UInt8[0x22, 0x80, 0x80, 0x80, 0x20], MyMessage) == PREFIX
        @test refused(UInt8[0x12, 0x05, 0x01, 0x00, 0x00, 0x00, 0x02], Blob) ==
              "protobuf packed field length is not a multiple of its element size"
    end

    @testset "nesting is capped at 100 levels" begin
        # Unknown groups, skipped: the recursion needs no schema at all.
        @test decoded(groups(100), MyMessage) isa MyMessage
        @test refused(groups(101), MyMessage) == DEPTH
        @test refused(groups(1_000), MyMessage) == DEPTH
        # A recursive message, current codegen.
        n = decoded(nodes(100), Node)
        @test n isa Node
        @test refused(nodes(101), Node) == DEPTH
        # One counter across both codegens and both kinds of nesting: `People` > `Person` puts
        # the groups one level down.
        inside_person(g) = (inner = groups(g); vcat(0x0a, varint(length(inner)), inner))
        @test decoded(inside_person(99), People) isa People
        @test refused(inside_person(100), People) == DEPTH
    end

    @testset "a body may cause 16 merges of singular sub-messages" begin
        MERGES = "protobuf body merges repeated singular sub-message fields more than 16 times"
        # Each repeat is `blob { fx: [1] }`; every merge after the first re-copies `fx`, so the
        # uncapped cost grows with the square of the body.
        repeats(n) = repeat(UInt8[0x0a, 0x05, 0x15, 0x01, 0x00, 0x00, 0x00], n)
        h = decoded(repeats(17), Holder)
        @test h.blob.fx == fill(UInt32(1), 17)
        @test refused(repeats(18), Holder) == MERGES
        # The count is per BODY, across fields and levels. Each level below carries an empty
        # `child` (`12 00`), then its real `child`, which merges into it: one merge per level, and
        # no field anywhere appears more than twice. (Empty first, not last: upstream's
        # `_merge_structs` has no method for a set sub-message merged with an unset one.)
        merge_per_level(n) = foldl((inner, _) -> vcat(0x12, 0x00, 0x12, varint(length(inner)), inner),
                                   1:n; init = UInt8[])
        @test decoded(merge_per_level(16), Node) isa Node
        @test refused(merge_per_level(17), Node) == MERGES
    end

    @testset "proto2 required sub-messages are not mistaken for merges" begin
        # Current codegen holds a `required` message field in a plain `Ref{T}()`, which for a
        # `T` laid out inline with no pointer reads as assigned before the field is seen. Counted
        # as a merge, 9 two-point lines -- 18 first occurrences, no repeats -- were refused.
        drawing = Drawing([Line(Point(i, i), Point(-i, 2i)) for i in 1:40])
        back = protobuf(protobuf(drawing, "/data"), Drawing)
        @test length(back.lines) == 40
        @test back.lines[end].b == Point(-40, 80)
        # Not only isbits types: `Labeled` holds an optional sub-message, a `Union{Nothing, Tag}`
        # field, and is still inline and pointer-free.
        table = Table([Row(Labeled(iseven(i) ? Tag(i) : nothing, i)) for i in 1:40])
        back = protobuf(protobuf(table, "/data"), Table)
        @test [r.item.k for r in back.rows] == 1:40
        @test back.rows[40].item.tag == Tag(40) && back.rows[39].item.tag === nothing
    end

    @testset "a proto2 required sub-message that can hold a vector is still capped" begin
        # The other half of the line drawn above: `Bag` holds a vector, so its merges are the
        # quadratic kind, and its `Ref{Bag}()` reads unassigned until the first occurrence.
        box(n) = repeat(UInt8[0x0a, 0x05, 0x0d, 0x01, 0x00, 0x00, 0x00], n)   # bag { v: [1] }
        @test protobuf(req(box(17)), Box).bag.v == fill(UInt32(1), 17)
        @test refused(box(18), Box) ==
              "protobuf body merges repeated singular sub-message fields more than 16 times"
    end

    @testset "a packed run after an unpacked element keeps both" begin
        # Upstream sized the packed run from the vector's grown capacity, so the elements it
        # returned after the unpacked one were uninitialized memory.
        b = decoded(UInt8[0x15, 7, 0, 0, 0, 0x12, 0x08, 1, 0, 0, 0, 2, 0, 0, 0], Blob)
        @test b.fx == UInt32[7, 1, 2]
        b = decoded(UInt8[0x1d, 0x00, 0x00, 0x80, 0x3f, 0x1a, 0x04, 0x00, 0x00, 0x00, 0x40], Blob)
        @test b.fl == Float32[1, 2]
    end

    @testset "well-formed messages still round-trip" begin
        blob = Blob(UInt8[1, 2, 3], UInt32[1, 2], Float32[1.5], [true, false])
        for r in (protobuf(protobuf(blob, "/data"), Blob), protobuf(protobuf(blob), Blob))
            @test (r.data, r.fx, r.fl, r.flags) == (blob.data, blob.fx, blob.fl, blob.flags)
        end
        chain = protobuf(protobuf(Node(1, Node(2, Node(3, nothing))), "/data"), Node)
        @test (chain.x, chain.child.x, chain.child.child.x, chain.child.child.child) == (1, 2, 3, nothing)
    end
end


end