module ProtoBufExt

import HTTP
import Nitro: ProtoBuffer, protobuf
import Nitro.Types: Param, LazyRequest
import Nitro.Extractors: Extractor, extract, try_validate, safe_extract
import ProtoBuf
import ProtoBuf: encode, decode, ProtoEncoder

export protobuf, extract

# HTTP.jl v2 stores request bodies as `AbstractBody` and may keep response bodies as a
# raw byte vector or string. Normalize any of these to bytes for protobuf decoding.
_pb_body_bytes(body::AbstractVector{UInt8}) = body
_pb_body_bytes(body::AbstractString) = codeunits(String(body))
_pb_body_bytes(::HTTP.EmptyBody) = UInt8[]
_pb_body_bytes(body::HTTP.BytesBody) = body.data

# ---------------------------------------------------------------------------------------------
# Bounded decoding (#325)
#
# ProtoBuf.jl's decoder believes what the wire format says about itself, and a request body is
# written by whoever sent it. Four consequences, each reachable with a few bytes and no auth:
#
#   * a string or packed fixed-width field ALLOCATES its length prefix before reading it, so
#     `0a ff ff ff ff 0f` (6 bytes) asks for 4 GiB -- `max_body_bytes` cannot help;
#   * a `bytes` field or a skipped unknown field with a lying prefix is silently TRUNCATED to
#     what is there, and the message decodes as if nothing were wrong;
#   * sub-messages and groups RECURSE once per level with no cap, so a body of nested group
#     tags overflows the stack -- a `StackOverflowError`, which `safe_extract` rightly refuses
#     to report as a 400, and on some Windows hosts a dead process (#301);
#   * a repeated singular sub-message field is MERGED into its earlier value each time, and each
#     merge re-copies every repeated field it holds, so the work grows with the square of the
#     body.
#
# Plus an upstream slip the packed rewrite below fixes in passing: packed fixed-width runs are
# sized from the vector's grown CAPACITY instead of its `occupied` count, so after one unpacked
# element the decoded field returns uninitialized memory.
#
# `_BoundedDecoder` is a decoder of our own, so every method below dispatches on a type this
# module owns -- no piracy. It must carry its type all the way down: for code generated by an
# older ProtoBuf.jl, upstream's `decode(d, Ref{T})` swaps in its own `LengthDelimitedProtoDecoder`
# for each sub-message, which is why the `Ref` methods are REPLACED here rather than wrapped.
#
# These methods key on ProtoBuf.jl internals under a `^1` compat bound. The attack bodies in
# test/extensions/protobuf/protobuf_tests.jl are the tripwire: if a 1.x release renames one of
# these, those tests fail rather than the bounds quietly ceasing to apply.
# ---------------------------------------------------------------------------------------------

const PBC = ProtoBuf.Codecs

"""
Deepest nesting of sub-messages and groups one body may carry — protobuf's own default recursion
limit. Internal and fixed, like `MAX_JSON_DEPTH`.
"""
const MAX_PROTOBUF_DEPTH = 100

"""
How many merges one body may cause in total: each time a singular sub-message field appears again
and is merged into its earlier value, across every field and every nesting level. Real encoders
only repeat one by concatenating whole messages. Internal and fixed.
"""
const MAX_PROTOBUF_MERGES = 16

# `io` is the field name `PBC.get_stream` reads. `endpos`/`group` are only used by code from an
# older ProtoBuf.jl, which asks the decoder itself where a sub-message ends (`message_done(d)`);
# current code passes both as arguments instead. The two counters are SHARED by every nested
# decoder, so one count covers current code (same decoder all the way down), older code (a fresh
# one per level), and group skips alike. They are never unwound on a throw, and need not be: the
# decoder is private to one `_decode_bounded` call, and nothing in ProtoBuf.jl catches an error
# partway through a decode, so a throw ends the only use of the counters.
struct _BoundedDecoder{I<:IO} <: PBC.AbstractProtoDecoder
    io::I
    endpos::Int
    group::Bool
    depth::Base.RefValue{Int}
    merges::Base.RefValue{Int}
end

_BoundedDecoder(io::IO) = _BoundedDecoder(io, 0, false, Ref(0), Ref(0))
_nested(d::_BoundedDecoder, endpos::Int, group::Bool) =
    _BoundedDecoder(d.io, endpos, group, d.depth, d.merges)

# Fixed messages that never quote the body, so `safe_extract`'s 400 carries nothing the sender
# wrote -- the convention `MAX_JSON_DEPTH` set for JSON (#314).
@noinline _throw_protobuf(msg::String) = throw(ArgumentError(msg))

# Read a length prefix, refusing one that claims more than the body has left.
function _read_prefix(io::IO)::Int
    len = PBC.vbyte_decode(io, UInt32)
    len <= bytesavailable(io) || _throw_protobuf("protobuf length prefix exceeds the remaining body")
    return Int(len)
end

function _enter!(d::_BoundedDecoder)
    (d.depth[] += 1) <= MAX_PROTOBUF_DEPTH ||
        _throw_protobuf("protobuf message nests deeper than $MAX_PROTOBUF_DEPTH levels")
    return nothing
end
_leave!(d::_BoundedDecoder) = (d.depth[] -= 1; nothing)

function _merged!(d::_BoundedDecoder)
    (d.merges[] += 1) <= MAX_PROTOBUF_MERGES ||
        _throw_protobuf("protobuf body merges repeated singular sub-message fields more than $MAX_PROTOBUF_MERGES times")
    return nothing
end

_decode_bounded(bytes::AbstractVector{UInt8}, ::Type{T}) where {T} =
    PBC.decode(_BoundedDecoder(IOBuffer(bytes)), T)

# -- Length-prefixed scalars -------------------------------------------------------------------

PBC.decode(d::_BoundedDecoder, ::Type{String}) = String(read(d.io, _read_prefix(d.io)))
PBC.decode(d::_BoundedDecoder, ::Type{Vector{UInt8}}) = read(d.io, _read_prefix(d.io))

# Packed fixed-width runs. Rewritten rather than wrapped, both for the prefix check and to fill
# from `occupied` -- see the header.
function PBC.decode!(d::_BoundedDecoder, w::PBC.WireType, buffer::PBC.BufferedVector{T},
                     ::Type{Val{:fixed}}) where {T<:Union{Int32,Int64,UInt32,UInt64}}
    if w == PBC.LENGTH_DELIMITED
        _decode_packed!(() -> PBC.decode(d, T, Val{:fixed}), buffer, _read_prefix(d.io))
    else
        buffer[] = PBC.decode(d, T, Val{:fixed})
    end
    return nothing
end

function PBC.decode!(d::_BoundedDecoder, w::PBC.WireType,
                     buffer::PBC.BufferedVector{T}) where {T<:Union{Bool,Float32,Float64}}
    if w == PBC.LENGTH_DELIMITED
        _decode_packed!(() -> PBC.decode(d, T), buffer, _read_prefix(d.io))
    else
        buffer[] = PBC.decode(d, T)
    end
    return nothing
end

# Each element of these types is exactly `sizeof(T)` bytes on the wire, so a run whose length is
# not a multiple of that is malformed rather than merely short.
function _decode_packed!(next::F, buffer::PBC.BufferedVector{T}, bytelen::Int) where {F,T}
    bytelen % sizeof(T) == 0 ||
        _throw_protobuf("protobuf packed field length is not a multiple of its element size")
    total = buffer.occupied + bytelen ÷ sizeof(T)
    length(buffer.elements) < total && resize!(buffer.elements, total)
    for i in (buffer.occupied + 1):total
        @inbounds buffer.elements[i] = next()
    end
    buffer.occupied = total
    return nothing
end

# -- Sub-messages and groups: depth, and keeping this decoder all the way down ------------------

# The same test upstream makes: current generated code has a 4-argument `decode` and takes the
# decoder it is given; older code has only `decode(d, T)` and asks `message_done(d)`.
_current_codegen(::Type{T}) where {T} =
    hasmethod(PBC.decode, Tuple{PBC.AbstractProtoDecoder, Type{T}, Int, Bool})

function PBC.decode(d::_BoundedDecoder, ::Type{Ref{T}}) where {T}
    io = d.io
    endpos = _read_prefix(io) + position(io)
    _enter!(d)
    out = _current_codegen(T) ? PBC.decode(d, T, endpos, false) :
                                PBC.decode(_nested(d, endpos, false), T)
    _leave!(d)
    position(io) == endpos ||
        _throw_protobuf("protobuf sub-message does not end where its length prefix says")
    return out
end

function PBC.decode(d::_BoundedDecoder, ::Type{Ref{T}}, ::Type{Val{:group}}) where {T}
    _enter!(d)
    out = _current_codegen(T) ? PBC.decode(d, T, 0, true) : PBC.decode(_nested(d, 0, true), T)
    _leave!(d)
    return out
end

# Current generated code calls the 3-argument form; older code the 1-argument one. Upstream's
# 3-argument method reads a `message_done` field this struct does not carry, and its
# length-delimited 1-argument method stops only on `==`, so a field that overruns its parent's
# end reads on into the parent. `>=` stops it, and the `Ref` methods above then refuse it.
function PBC.message_done(d::_BoundedDecoder, endpos::Int, group::Bool)
    io = d.io
    if group
        done = peek(io) == UInt8(PBC.END_GROUP)
        done && skip(io, 1)
        return done
    end
    return eof(io) || (endpos > 0 && position(io) >= endpos)
end
PBC.message_done(d::_BoundedDecoder) = PBC.message_done(d, d.endpos, d.group)

# Unknown fields. Upstream's group skip calls `skip(d, …)` for each field inside the group, which
# dispatches back here, so every nesting level passes through `_enter!`.
function Base.skip(d::_BoundedDecoder, wire_type::PBC.WireType)
    if wire_type == PBC.LENGTH_DELIMITED
        skip(d.io, _read_prefix(d.io))
    elseif wire_type == PBC.START_GROUP
        _enter!(d)
        invoke(Base.skip, Tuple{PBC.AbstractProtoDecoder, PBC.WireType}, d, wire_type)
        _leave!(d)
    else
        invoke(Base.skip, Tuple{PBC.AbstractProtoDecoder, PBC.WireType}, d, wire_type)
    end
    return nothing
end

# -- Merges of a repeated singular sub-message field -------------------------------------------

# Counted here, then handed to upstream, which does the merge itself. All four signatures are
# needed: the `S>:Nothing` pair is what current generated code uses for an optional field
# (`Ref{Union{Nothing,T}}`), and defining only the plain pair would leave those calls ambiguous
# against upstream's.
#
# The plain pair holds proto2 `required` fields, in a `Ref{T}()`. When `T` is stored inline and
# its layout holds no pointer, that ref reads as ASSIGNED before the field is ever seen, so
# `isassigned` cannot tell a first occurrence from a repeat -- counting it refused ordinary
# messages. That is not only isbits types: a message whose `optional` sub-message field is
# `Union{Nothing, <isbits>}` is laid out inline too. Such a `T` need not be counted anyway: with
# no pointer it holds no vector, so merging one is O(1), and the quadratic cost this cap exists
# for cannot arise. Any `T` that CAN hold a vector has a pointer, and there `isassigned` is
# reliable. (`allocatedinline` alone is not the test: a struct holding a `Vector` is inline too.)
_counts_merge(buffer::Base.RefValue{T}) where {T} =
    !(Base.allocatedinline(T) && Base.datatype_pointerfree(T)) && isassigned(buffer)

function PBC.decode!(d::_BoundedDecoder, buffer::Base.RefValue{S}) where {S>:Nothing}
    isnothing(buffer[]) || _merged!(d)
    return invoke(PBC.decode!, Tuple{PBC.AbstractProtoDecoder, Base.RefValue{S}}, d, buffer)
end
function PBC.decode!(d::_BoundedDecoder, buffer::Base.RefValue{T}) where {T}
    _counts_merge(buffer) && _merged!(d)
    return invoke(PBC.decode!, Tuple{PBC.AbstractProtoDecoder, Base.RefValue{T}}, d, buffer)
end
function PBC.decode!(d::_BoundedDecoder, buffer::Base.RefValue{S},
                     ::Type{Val{:group}}) where {S>:Nothing}
    isnothing(buffer[]) || _merged!(d)
    return invoke(PBC.decode!, Tuple{PBC.AbstractProtoDecoder, Base.RefValue{S}, Type{Val{:group}}},
                  d, buffer, Val{:group})
end
function PBC.decode!(d::_BoundedDecoder, buffer::Base.RefValue{T}, ::Type{Val{:group}}) where {T}
    _counts_merge(buffer) && _merged!(d)
    return invoke(PBC.decode!, Tuple{PBC.AbstractProtoDecoder, Base.RefValue{T}, Type{Val{:group}}},
                  d, buffer, Val{:group})
end

"""
    protobuf(request::HTTP.Request, type::Type{T}) :: T where {T}

Decode a protobuf message from the body of an HTTP request.

The decode is bounded, because the body is written by whoever sent it (#325). A body is
refused with an `ArgumentError` that never quotes it if:

- a string, bytes, packed fixed-width, sub-message or skipped unknown field has a length
  prefix claiming more bytes than the body has left;
- sub-messages and groups nest deeper than 100 levels;
- repeated singular sub-message fields cause more than 16 merges in the body as a whole;
- a packed fixed-width field's length is not a multiple of its element size.

Other malformed bodies still fail with ProtoBuf.jl's own errors, for example an `EOFError` for
a body that ends mid-field. A direct caller treating a bad body as the client's fault should
therefore catch every exception except `InterruptException`, `StackOverflowError` and
`OutOfMemoryError`. The `ProtoBuffer{T}` extractor already does that: every one of these is a
`400` through it.

# Arguments
- `request`: An HTTP request object containing the protobuf message in its body.
- `type`: The type of the protobuf message to decode.

# Returns
- The decoded protobuf message of the specified type.
"""
function protobuf(request::HTTP.Request, type::Type{T}) :: T where {T}
    return _decode_bounded(_pb_body_bytes(request.body), type)
end

"""
    protobuf(response::HTTP.Response, type::Type{T}) :: T where {T}

Decode a protobuf message from the body of an HTTP response, under the same bounds as
`protobuf(request, T)`. A response comes from whichever server answered, so it gets no more trust
than a request does.
"""
function protobuf(response::HTTP.Response, type::Type{T}) :: T where {T}
    return _decode_bounded(_pb_body_bytes(response.body), type)
end

"""
    protobuf(content::T, url::String, method::String = "POST") :: HTTP.Request where {T}

Encode a protobuf message into the body of an HTTP.Request

# Arguments
- `content`: The protobuf message to encode.
- `target`: The target (URL) to which the request will be sent.
- `method`: The HTTP method for the request (default is "POST").
- `headers`: The HTTP headers for the request (default is an empty list).

# Returns
- An HTTP request object with the encoded protobuf message in its body.
"""
function protobuf(content::T, target::String; method = "POST", headers = []) :: HTTP.Request where {T}
    io = IOBuffer()
    encode(ProtoEncoder(io), content)
    body = take!(io)
    # Format the request
    request = HTTP.Request(method, target, headers, body)
    HTTP.setheader(request, "Content-Type" => "application/octet-stream")
    HTTP.setheader(request, "Content-Length" => string(sizeof(body)))
    return request
end


"""
    protobuf(content::T; status = 200, headers = []) :: HTTP.Response where {T}

Encode a protobuf message into the body of an HTTP.Response

# Arguments
- `content`: The protobuf message to encode.
- `status`: The HTTP status code for the response (default is 200).
- `headers`: The HTTP headers for the response (default is an empty list).

# Returns
- An HTTP response object with the encoded protobuf message in its body.
"""
function protobuf(content::T; status = 200, headers = []) :: HTTP.Response where {T}
    io = IOBuffer()
    encode(ProtoEncoder(io), content)
    body = take!(io)
    # Format the response
    response = HTTP.Response(status, headers, body = body)
    HTTP.setheader(response, "Content-Type" => "application/octet-stream")
    HTTP.setheader(response, "Content-Length" => string(sizeof(body)))
    return response
end

"""
Extracts a Protobuf message from a request and converts it into a custom struct.

The body is decoded under the bounds `protobuf(request, T)` documents, and a body that breaks
them is a `400`.
"""
function extract(param::Param{ProtoBuffer{T}}, request::LazyRequest) :: ProtoBuffer{T} where {T}
    instance = safe_extract(param) do 
        protobuf(request.request, T)
    end
    valid_instance = try_validate(param, instance)
    return ProtoBuffer(valid_instance)
end


end