# Autogenerated using ProtoBuf.jl v1.3.0
# original file: bounds.proto (proto3 syntax)

module bounds_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Blob, Node, Holder


struct Blob
    data::Vector{UInt8}
    fx::Vector{UInt32}
    fl::Vector{Float32}
    flags::Vector{Bool}
end
PB.default_values(::Type{Blob}) = (;data = UInt8[], fx = Vector{UInt32}(), fl = Vector{Float32}(), flags = Vector{Bool}())
PB.field_numbers(::Type{Blob}) = (;data = 1, fx = 2, fl = 3, flags = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Blob}, _endpos::Int=0, _group::Bool=false)
    data = UInt8[]
    fx = PB.BufferedVector{UInt32}()
    fl = PB.BufferedVector{Float32}()
    flags = PB.BufferedVector{Bool}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            data = PB.decode(d, Vector{UInt8})
        elseif field_number == 2
            PB.decode!(d, wire_type, fx, Val{:fixed})
        elseif field_number == 3
            PB.decode!(d, wire_type, fl)
        elseif field_number == 4
            PB.decode!(d, wire_type, flags)
        else
            Base.skip(d, wire_type)
        end
    end
    return Blob(data, fx[], fl[], flags[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Blob)
    initpos = position(e.io)
    !isempty(x.data) && PB.encode(e, 1, x.data)
    !isempty(x.fx) && PB.encode(e, 2, x.fx, Val{:fixed})
    !isempty(x.fl) && PB.encode(e, 3, x.fl)
    !isempty(x.flags) && PB.encode(e, 4, x.flags)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Blob)
    encoded_size = 0
    !isempty(x.data) && (encoded_size += PB._encoded_size(x.data, 1))
    !isempty(x.fx) && (encoded_size += PB._encoded_size(x.fx, 2, Val{:fixed}))
    !isempty(x.fl) && (encoded_size += PB._encoded_size(x.fl, 3))
    !isempty(x.flags) && (encoded_size += PB._encoded_size(x.flags, 4))
    return encoded_size
end

struct Node
    x::Int64
    child::Union{Nothing,Node}
end
PB.default_values(::Type{Node}) = (;x = zero(Int64), child = nothing)
PB.field_numbers(::Type{Node}) = (;x = 1, child = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Node}, _endpos::Int=0, _group::Bool=false)
    x = zero(Int64)
    child = Ref{Union{Nothing,Node}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            x = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, child)
        else
            Base.skip(d, wire_type)
        end
    end
    return Node(x, child[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Node)
    initpos = position(e.io)
    x.x != zero(Int64) && PB.encode(e, 1, x.x)
    !isnothing(x.child) && PB.encode(e, 2, x.child)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Node)
    encoded_size = 0
    x.x != zero(Int64) && (encoded_size += PB._encoded_size(x.x, 1))
    !isnothing(x.child) && (encoded_size += PB._encoded_size(x.child, 2))
    return encoded_size
end

struct Holder
    blob::Union{Nothing,Blob}
end
PB.default_values(::Type{Holder}) = (;blob = nothing)
PB.field_numbers(::Type{Holder}) = (;blob = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Holder}, _endpos::Int=0, _group::Bool=false)
    blob = Ref{Union{Nothing,Blob}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, blob)
        else
            Base.skip(d, wire_type)
        end
    end
    return Holder(blob[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Holder)
    initpos = position(e.io)
    !isnothing(x.blob) && PB.encode(e, 1, x.blob)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Holder)
    encoded_size = 0
    !isnothing(x.blob) && (encoded_size += PB._encoded_size(x.blob, 1))
    return encoded_size
end
end # module
