# Autogenerated using ProtoBuf.jl v1.3.0
# original file: bounds2.proto (proto2 syntax)

module bounds2_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Point, Tag, Bag, Line, Labeled, Box, Drawing, Row, Table


struct Point
    x::Int32
    y::Int32
end
PB.default_values(::Type{Point}) = (;x = zero(Int32), y = zero(Int32))
PB.field_numbers(::Type{Point}) = (;x = 1, y = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Point}, _endpos::Int=0, _group::Bool=false)
    x = zero(Int32)
    y = zero(Int32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            x = PB.decode(d, Int32)
        elseif field_number == 2
            y = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return Point(x, y)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Point)
    initpos = position(e.io)
    PB.encode(e, 1, x.x)
    PB.encode(e, 2, x.y)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Point)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.x, 1)
    encoded_size += PB._encoded_size(x.y, 2)
    return encoded_size
end

struct Tag
    id::Int32
end
PB.default_values(::Type{Tag}) = (;id = zero(Int32))
PB.field_numbers(::Type{Tag}) = (;id = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Tag}, _endpos::Int=0, _group::Bool=false)
    id = zero(Int32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return Tag(id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Tag)
    initpos = position(e.io)
    PB.encode(e, 1, x.id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Tag)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.id, 1)
    return encoded_size
end

struct Bag
    v::Vector{UInt32}
end
PB.default_values(::Type{Bag}) = (;v = Vector{UInt32}())
PB.field_numbers(::Type{Bag}) = (;v = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Bag}, _endpos::Int=0, _group::Bool=false)
    v = PB.BufferedVector{UInt32}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, v, Val{:fixed})
        else
            Base.skip(d, wire_type)
        end
    end
    return Bag(v[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Bag)
    initpos = position(e.io)
    !isempty(x.v) && PB.encode(e, 1, x.v, Val{:fixed})
    return position(e.io) - initpos
end
function PB._encoded_size(x::Bag)
    encoded_size = 0
    !isempty(x.v) && (encoded_size += PB._encoded_size(x.v, 1, Val{:fixed}))
    return encoded_size
end

struct Line
    a::Point
    b::Point
end
PB.default_values(::Type{Line}) = (;a, b)
PB.field_numbers(::Type{Line}) = (;a = 1, b = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Line}, _endpos::Int=0, _group::Bool=false)
    a = Ref{Point}()
    b = Ref{Point}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, a)
        elseif field_number == 2
            PB.decode!(d, b)
        else
            Base.skip(d, wire_type)
        end
    end
    return Line(a[], b[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Line)
    initpos = position(e.io)
    PB.encode(e, 1, x.a)
    PB.encode(e, 2, x.b)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Line)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.a, 1)
    encoded_size += PB._encoded_size(x.b, 2)
    return encoded_size
end

struct Labeled
    tag::Union{Nothing,Tag}
    k::Int32
end
PB.default_values(::Type{Labeled}) = (;tag = nothing, k = zero(Int32))
PB.field_numbers(::Type{Labeled}) = (;tag = 1, k = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Labeled}, _endpos::Int=0, _group::Bool=false)
    tag = Ref{Union{Nothing,Tag}}(nothing)
    k = zero(Int32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, tag)
        elseif field_number == 2
            k = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return Labeled(tag[], k)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Labeled)
    initpos = position(e.io)
    !isnothing(x.tag) && PB.encode(e, 1, x.tag)
    PB.encode(e, 2, x.k)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Labeled)
    encoded_size = 0
    !isnothing(x.tag) && (encoded_size += PB._encoded_size(x.tag, 1))
    encoded_size += PB._encoded_size(x.k, 2)
    return encoded_size
end

struct Box
    bag::Bag
end
PB.default_values(::Type{Box}) = (;bag)
PB.field_numbers(::Type{Box}) = (;bag = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Box}, _endpos::Int=0, _group::Bool=false)
    bag = Ref{Bag}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, bag)
        else
            Base.skip(d, wire_type)
        end
    end
    return Box(bag[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Box)
    initpos = position(e.io)
    PB.encode(e, 1, x.bag)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Box)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.bag, 1)
    return encoded_size
end

struct Drawing
    lines::Vector{Line}
end
PB.default_values(::Type{Drawing}) = (;lines = Vector{Line}())
PB.field_numbers(::Type{Drawing}) = (;lines = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Drawing}, _endpos::Int=0, _group::Bool=false)
    lines = PB.BufferedVector{Line}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, lines)
        else
            Base.skip(d, wire_type)
        end
    end
    return Drawing(lines[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Drawing)
    initpos = position(e.io)
    !isempty(x.lines) && PB.encode(e, 1, x.lines)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Drawing)
    encoded_size = 0
    !isempty(x.lines) && (encoded_size += PB._encoded_size(x.lines, 1))
    return encoded_size
end

struct Row
    item::Labeled
end
PB.default_values(::Type{Row}) = (;item)
PB.field_numbers(::Type{Row}) = (;item = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Row}, _endpos::Int=0, _group::Bool=false)
    item = Ref{Labeled}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, item)
        else
            Base.skip(d, wire_type)
        end
    end
    return Row(item[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Row)
    initpos = position(e.io)
    PB.encode(e, 1, x.item)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Row)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.item, 1)
    return encoded_size
end

struct Table
    rows::Vector{Row}
end
PB.default_values(::Type{Table}) = (;rows = Vector{Row}())
PB.field_numbers(::Type{Table}) = (;rows = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Table}, _endpos::Int=0, _group::Bool=false)
    rows = PB.BufferedVector{Row}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, rows)
        else
            Base.skip(d, wire_type)
        end
    end
    return Table(rows[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Table)
    initpos = position(e.io)
    !isempty(x.rows) && PB.encode(e, 1, x.rows)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Table)
    encoded_size = 0
    !isempty(x.rows) && (encoded_size += PB._encoded_size(x.rows, 1))
    return encoded_size
end
end # module
